#!/usr/bin/env python3
"""Generate per-bug ticket files from in-script catalog.

Run from repo root:
    python scripts/ai/bug_tracker/generate_tickets.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parents[3] / "docs" / "ai" / "tickets" / "2026-04-29-output-quality"

# (id, title, channel, vendor, dup_of, severity, hypothesis, raw_evidence, fix_target)
TICKETS = [
    ("B01", "GPU(Tesla T4)가 CPU 섹션에 합쳐짐", "redfish", "dell", None, "high",
     "redfish_gather가 /Systems/.../Processors/ 컬렉션에서 ProcessorType=='CPU' 필터를 안 걸고 모든 Processor를 cpu.summary.groups에 합산. r760-1만 GPU 1장 장착이라 다른 host와 결과 차이.",
     "Processors/ 각 멤버의 ProcessorType / Manufacturer 필드 확인",
     "redfish-gather/library/redfish_gather.py + adapters/redfish/redfish_generic.yml normalize.cpu"),
    ("B02", "Redfish DNS unspecified IP(0.0.0.0/::) 그대로 노출", "redfish", "dell/hpe/lenovo", None, "high",
     "Redfish는 ManagerNetworkProtocol/EthernetInterface.NameServers를 그대로 emit. BMC가 DNS 미설정이면 0.0.0.0/::이 응답에 들어옴. unspecified IP 필터 부재.",
     "/Managers/.../EthernetInterfaces/.../NameServers 응답값",
     "redfish-gather/library/redfish_gather.py 의 dns_servers 정규화"),
    ("B03", "Redfish failed envelope 정합성 깨짐", "redfish", "dell", None, "high",
     "redfish-gather/site.yml always block의 fallback envelope이 system/hardware/bmc/cpu/memory/power은 None, storage/network/users/firmware는 빈 dict/list로 채움 — 일관성 부재.",
     "site.yml의 always 블록 + build_output.yml의 데이터 구조",
     "common/tasks/normalize/build_output.yml 또는 redfish-gather/site.yml always 블록"),
    ("B04", "Ubuntu DNS=127.0.0.53 (systemd-resolved stub)", "os", "linux", None, "high",
     "Linux gather_network이 /etc/resolv.conf만 보고 nameserver를 추출. Ubuntu는 systemd-resolved stub resolver(127.0.0.53)이라 실 upstream DNS는 resolvectl status / /run/systemd/resolve/resolv.conf 또는 /etc/systemd/resolved.conf 봐야 함.",
     "Ubuntu host에서 resolvectl status + /etc/resolv.conf + /run/systemd/resolve/resolv.conf 비교",
     "os-gather/tasks/linux/collect_dns.yml 또는 gather_network.yml"),
    ("B05", "RHEL 8.10 raw_fallback cpu.summary.groups=[]", "os", "linux", None, "med",
     "raw fallback 모드(_l_python_mode=python_incompatible)에서 build_cpu의 summary.groups 빌드 단계 skip. 다른 host(python_ok)는 1 group 채움.",
     "10.100.64.161 raw 모드 lscpu 출력 + Ansible 변수 dump",
     "os-gather/tasks/linux/normalize_cpu.yml raw 분기"),
    ("B06", "ESXi network.summary.groups buggy", "esxi", "vmware", None, "high",
     "esxi-gather normalize_network 빌더가 adapters를 speed/link_type 키로 group_by 하는데 모든 adapter가 speed=null이면 1개 그룹 + quantity=1로 잘못 계산.",
     "esxi host adapters dump (speed_mbps null 분포)",
     "esxi-gather/tasks/normalize_network.yml summary 빌더"),
    ("B07", "Redfish system.* 모두 None인데 sections.system='success'", "redfish", "all", None, "high",
     "Redfish는 OS 정보 없음 → system 섹션을 채우지 못함. 그러나 build_status가 system을 'success'로 마크. 'not_supported' 또는 BMC 정보 매핑 필요. rule 22 status_rules.",
     "redfish-gather에서 system 섹션 빌드 위치 + sections_supported_fragment 확인",
     "redfish-gather/tasks/normalize_system.yml + supported_sections"),
    ("B08", "BMC.product/mac/hostname 모두 None", "redfish", "all", None, "med",
     "Redfish manager 정보 추출 시 product(iDRAC9/iLO6/XCC/CIMC), mac(EthernetInterface), hostname(HostName) 필드 매핑 누락. firmware_version만 채워짐.",
     "/Managers/.../* 응답 + EthernetInterfaces",
     "redfish-gather/library/redfish_gather.py bmc 추출"),
    ("B09", "memory.slots[*].locator 모두 None", "redfish", "all", None, "high",
     "Redfish Memory.DeviceLocator 또는 MemoryLocation.Slot 추출 누락. DIMM 위치(예: A1) 모르면 교체 작업 불가.",
     "/Systems/.../Memory/{id} 의 DeviceLocator/MemoryLocation",
     "redfish-gather/library/redfish_gather.py memory.slots"),
    ("B10", "physical_disks[*].capacity_gb 모두 None", "redfish", "all", None, "high",
     "Redfish Drive.CapacityBytes 추출 누락. logical_volumes의 total은 정상이지만 disk 단위 용량 None.",
     "/Systems/.../Storage/.../Drives/{id} 의 CapacityBytes",
     "redfish-gather/library/redfish_gather.py physical_disks"),
    ("B11", "GPU group total_cores=0 (B1 부산물)", "redfish", "dell", "B01", "low", None, None, None),
    ("B12", "firmware.component vendor마다 ID 형식 다름", "redfish", "all", None, "med",
     "Dell ID 숫자, HPE 인덱스, Lenovo 'BMC-AFBT-10', Cisco 'slot-L'. 호출자가 cross-vendor 매칭 어려움. component_id + component_kind 분리 필요.",
     "각 vendor firmware 응답의 Id/Name 형식",
     "redfish-gather/library + adapter normalize.firmware"),
    ("B13", "interfaces.link_status 표기 비일관", "redfish", "all", None, "med",
     "Dell linkup/linkdown vs HPE/Cisco none. 표준 enum {up, down, unknown} 정규화 필요.",
     "각 vendor EthernetInterface.LinkStatus / LinkState 응답값",
     "redfish-gather/library normalize_link_status"),
    ("B14", "interfaces.name vendor마다 의미 다름", "redfish", "all", None, "low",
     "Dell 'System Ethernet Interface', HPE 숫자, Lenovo 'Host Ethernet Interface', Cisco 'Ethernet Interface'. 정규화 또는 의미 명시.",
     "각 vendor EthernetInterface.Name 응답값",
     "redfish-gather/library + adapter normalize.network"),
    ("B15", "data.users=[] but sections.users='not_supported'", "redfish", "all", None, "med",
     "Redfish AccountService로 계정 정보 수집 가능한데 정책상 not_supported. 결정 필요: 수집 vs not_supported.",
     "/AccountService/Accounts 응답 가능 여부",
     "정책 결정 + 옵션 redfish-gather/tasks/collect_users.yml"),
    ("B16", "bios_date 형식 vendor마다 다름", "redfish/esxi", "all", None, "med",
     "Dell 'MM/DD/YYYY', ESXi ISO 8601, HPE/Lenovo/Cisco null (bios_version에 inline). ISO 8601 통일.",
     "각 vendor BIOS.ReleaseDate / Bios.Date 응답값",
     "redfish-gather/library + esxi normalize_hardware"),
    ("B17", "Linux users.username 모두 None", "os", "linux", None, "high",
     "gather_users가 getent passwd에서 uid/groups만 추출, username 추출 누락. uid=0 groups=['root']인데 username=None.",
     "getent passwd 출력 + raw fallback의 awk 파싱",
     "os-gather/tasks/linux/gather_users.yml + raw 분기"),
    ("B18", "system.hostname=None (fqdn만 채워짐)", "os", "linux", None, "med",
     "gather_system이 ansible_hostname / ansible_fqdn 둘 다 setup에서 가져오지만 system.hostname 매핑 누락.",
     "ansible_facts.hostname / fqdn / nodename 비교",
     "os-gather/tasks/linux/normalize_system.yml + raw 분기"),
    ("B19", "r760-6 baremetal hardware 미수집", "os", "linux baremetal", None, "high",
     "gather_hardware가 hosting_type=virtual이면 skip하는 분기인데 baremetal에서도 dmidecode 호출 안 됨. _l_python_mode=python_ok에서 dmidecode 분기 누락.",
     "베어메탈 host에서 dmidecode 가능 여부",
     "os-gather/tasks/linux/gather_hardware.yml 분기"),
    ("B20", "VM CPU sockets=4 cores=4 threads=4", "os", "linux VM", None, "low",
     "lscpu의 Socket(s) 정보를 우선 사용 안 함. ansible_processor_count가 4(VM 노출)라 그대로 sockets=4. 관찰.",
     "VM에서 lscpu vs setup 차이",
     "os-gather/tasks/linux/normalize_cpu.yml"),
    ("B21", "RHEL 8.10 raw fallback summary.groups (B5 동일)", "os", "linux", "B05", "med", None, None, None),
    ("B22", "VM cpu.max_speed_mhz=None", "os", "linux VM", None, "med",
     "ansible_processor_mhz가 VM에선 없을 수 있음. lscpu의 'CPU max MHz' 또는 /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq fallback.",
     "VM lscpu max MHz 출력",
     "os-gather/tasks/linux/normalize_cpu.yml"),
    ("B23", "r760-6 memory.mfg=00AD063200AD raw hex", "os", "linux", None, "med",
     "dmidecode -t memory의 Manufacturer가 raw hex JEDEC code (0xAD = SK Hynix). JEDEC ID -> name 매핑 필요.",
     "r760-6에서 dmidecode -t memory 출력",
     "os-gather/tasks/linux/normalize_memory.yml + JEDEC map"),
    ("B24", "r760-6 memory.speed Redfish 4400 vs OS 5600 drift", "cross", "dell", None, "med",
     "Redfish OperatingSpeedMhz(4400) vs OS dmidecode Speed(5600 = SPD MaxClock). 의미 다름.",
     "Redfish vs dmidecode speed 필드 의미",
     "schema/field_dictionary.yml + envelope 의미 정의"),
    ("B25", "Linux storage.physical_disks.capacity_gb=None", "os", "linux", None, "high",
     "/sys/block/{dev}/size * 512 / 1e9 또는 lsblk -b로 추출 가능한데 누락.",
     "/sys/block 또는 lsblk 출력",
     "os-gather/tasks/linux/normalize_storage.yml + raw 분기"),
    ("B26", "Linux filesystem.fstype=None", "os", "linux", None, "med",
     "df -T 또는 mount/findmnt -t에서 추출. 현재 빌더가 mount_point/device/total만 추출.",
     "df -T / findmnt 출력",
     "os-gather/tasks/linux/normalize_storage.yml filesystems"),
    ("B27", "RHEL VM tz=America/New_York (관찰)", "os", "linux", None, "low", None, None, None),
    ("B28", "r760-6 baremetal hardware (B19 동일)", "os", "linux", "B19", "high", None, None, None),
    ("B29", "Linux disk media_type 부정확", "os", "linux", None, "low",
     "/sys/block/{dev}/queue/rotational만 보고 SSD/HDD 결정. RAID 가상 디스크는 0이라 SSD로 잘못 분류.",
     "/sys/block/queue/rotational + smartctl -i",
     "관찰 — OS-level 한계"),
    ("B30", "esxi03 vmnic1 누락", "esxi", "vmware", None, "med",
     "esxi01/02는 6 vmnic, esxi03만 5. 실 hw 차이인지 누락인지 검증 필요.",
     "esxi03에 esxcli network nic list로 실 NIC count",
     "esxi-gather/tasks/collect_facts.yml + esxi03 환경"),
    ("B31", "ESXi runtime tz/ntp/firewall 모두 None", "esxi", "vmware", None, "high",
     "esxcli system time get / ntp policy / esxcli network firewall get 미사용.",
     "esxcli 위 명령들 실행 가능 여부",
     "esxi-gather/tasks/collect_runtime.yml (신규?)"),
    ("B32", "ESXi network.default_gateways=[]", "esxi", "vmware", None, "high",
     "vSphere host_system.config.network.routeConfig.defaultGateway 또는 esxcli network ip route 미사용.",
     "esxcli network ip route ipv4 list / vsphere routeConfig",
     "esxi-gather/tasks/normalize_network.yml"),
    ("B33", "ESXi network.summary.groups (B6 동일)", "esxi", "vmware", "B06", "high", None, None, None),
    ("B34", "ESXi physical_disks=[]", "esxi", "vmware", None, "med",
     "vSphere host_system.config.storageDevice.scsiLun 또는 esxcli storage core device list.",
     "esxcli storage core device list 출력",
     "esxi-gather/tasks/collect_storage.yml"),
    ("B35", "ESXi storage.controllers=[]", "esxi", "vmware", None, "low",
     "정책 결정.", None, "정책"),
    ("B36", "ESXi HBA 개수가 host별 다름", "esxi", "vmware", None, "low", None, None, None),
    ("B37", "ESXi auth.attempted_count=2 fallback_used=false", "esxi", "vmware", None, "low",
     "fallback_used 산출 로직 모순.",
     "esxi-gather/tasks/auth.yml의 fallback_used 산출 로직",
     "esxi-gather/tasks/auth.yml"),
    ("B38", "ESXi memory.installed_mb=null (한계)", "esxi", "vmware", None, "low", None, None, None),
    ("B39", "ESXi sections.users=not_supported (정책)", "esxi", "vmware", None, "low", None, None, None),
    ("B40", "Ansible reserved variable 'name' warning", "global", "all", None, "low",
     "Ansible 2.20에서 reserved. 변수명 변경.",
     "ansible-playbook -vvv로 변수 위치 추적",
     "각 task의 'name' 변수 사용처"),
    ("B41", "Dell PSU=1 — PS2 누락 의심", "redfish", "dell", None, "high",
     "/Chassis/.../Power의 PowerSupplies collection에 PS2 있는지 확인. 1개만 노출됐는지 실 raw 응답 필수.",
     "/Chassis/System.Embedded.1/Power.PowerSupplies 전체 응답",
     "redfish-gather/library/redfish_gather.py power.power_supplies"),
    ("B42", "Dell PowerControl 6개 (의미 불명)", "redfish", "dell", "B46", "low",
     "B46 builder bug와 관련", None, "B46"),
    ("B43", "Lenovo firmware version=None 2건 (Pending)", "redfish", "lenovo", None, "low",
     "BMC-Primary-Pending, UEFI-Pending entry. version=null이지만 pending=true 같은 메타필드.",
     "Lenovo /UpdateService/FirmwareInventory 응답",
     "redfish-gather/library normalize_firmware"),
    ("B44", "Lenovo firmware naming (B12 동일)", "redfish", "lenovo", "B12", "low", None, None, None),
    ("B45", "Dell PSU PS2 누락 (B41 동일)", "redfish", "dell", "B41", "high", None, None, None),
    ("B46", "power.power_control = list of strings (builder bug)", "redfish", "all", None, "high",
     "PowerControl이 dict인데 빌더가 dict.keys() 또는 list of strings로 만들어버림. 결과: ['power_consumed_watts','power_capacity_watts',...] 형태.",
     "redfish_gather.py에서 power_control 추출 코드",
     "redfish-gather/library/redfish_gather.py power_control 추출"),
    ("B47", "esxi03 vmnic1 (B30 동일)", "esxi", "vmware", "B30", "med", None, None, None),
    ("B48", "Cisco logical_volume.name='' 빈 문자열", "redfish", "cisco", None, "low",
     "CIMC가 volume Name을 빈 문자열로 emit. fallback: 'Volume {id}' 또는 raid_level 기반.",
     "Cisco /Systems/.../Storage/.../Volumes/{id}.Name 응답",
     "redfish-gather/library normalize_volume"),
    ("B49", "Dell BOSS volumes boot_volume=false", "redfish", "dell", None, "low",
     "Dell BOSS-N1은 부팅 디스크인데 Redfish가 boot_volume false. Dell의 boot marker는 다른 위치(SystemBootDevice / Volumes.LinksBootedTo).",
     "Dell /Systems/.../BootSources / Volumes.Links 응답",
     "redfish-gather/library normalize_volume Dell 분기"),
    ("B50", "duration_ms 1초 단위 절삭", "global", "all", None, "med",
     "build_meta가 (finished-started)초 단위로 측정 후 *1000 — 실제는 ms까지 정밀 가능.",
     "build_meta.yml의 duration_ms 계산 식",
     "common/tasks/normalize/build_meta.yml"),
    ("B51", "Memory total/slots 합계 (OK)", "redfish", "all", None, "low", None, None, None),
    ("B52", "storage.grand_total_gb 의미 비일관", "redfish", "all", None, "med",
     "HPE/Lenovo는 RAID raw=2× usable, Dell r6 6GB drift. raw_capacity vs usable_capacity 분리.",
     "각 vendor Volume.CapacityBytes 의미",
     "schema/field_dictionary.yml + redfish-gather normalize_storage"),
    ("B53", "correlation.bmc_ip == host_ip (정책)", "redfish", "all", None, "low", None, None, None),
    ("B54", "Dell UUID prefix 4c4c4544 (정상 - 관찰)", "redfish", "dell", None, "low", None, None, None),
    ("B55", "failed envelope diagnosis.details 키 누락", "redfish", "dell", None, "med",
     "failed envelope에 account_service / auth 키 누락.",
     "site.yml always 블록에서 detail 합산",
     "redfish-gather/site.yml always 블록"),
    ("B56", "failed envelope auth_success=null", "redfish", "all", None, "med",
     "auth 시도 안 했으면 'not_attempted' 또는 false로 명시.",
     "build_diagnosis.yml의 auth_success 산출",
     "common/tasks/normalize/build_diagnosis.yml"),
    ("B57", "iface[*].mac != adapter[*].mac", "redfish", "all", None, "med",
     "interfaces=EthernetInterface(논리), adapters=NetworkAdapter(물리). 의미 정의 명시.",
     "각 vendor 두 컬렉션 응답 비교",
     "schema/field_dictionary.yml + envelope 의미 정의"),
    ("B58", "PSU Critical 알람이 summary에 노출 안 됨", "redfish", "hpe/lenovo", None, "high",
     "power_supplies[*].health=Critical인데 summary에 critical_count / unhealthy_count 없음.",
     "각 vendor PSU.Status.Health 분포",
     "redfish-gather/library power.summary 빌더"),
    ("B59", "Lenovo PSU total_capacity_w=750 (None 합산 버그)", "redfish", "lenovo", None, "high",
     "PSU#1.PowerCapacityWatts=null, PSU#2=750. summary가 null+750=750으로 합산.",
     "Lenovo PSU.PowerCapacityWatts 응답",
     "redfish-gather/library power.summary 빌더"),
    ("B60", "storage.grand_total_gb (B52 동일)", "redfish", "all", "B52", "med", None, None, None),
    ("B61", "hardware.oem coverage 비대칭 (Lenovo 1, Cisco 0)", "redfish", "lenovo/cisco", None, "med",
     "Dell 12 keys, HPE 7, Lenovo 1, Cisco 0. Lenovo Oem.Lenovo / Cisco Oem.Cisco 추출 보강.",
     "각 vendor /Chassis/.../Oem.{vendor} 응답",
     "redfish-gather/tasks/vendors/{lenovo,cisco}/collect_oem.yml"),
    ("B62", "ESXi diagnosis.details에 esxi_version 없음", "esxi", "vmware", None, "low",
     "Redfish는 redfish_version, OS는 detected_os 노출. ESXi도 esxi_version 노출.",
     "vSphere host_system.config.product 응답",
     "esxi-gather/tasks/diagnosis.yml"),
    ("B63", "OS diagnosis.auth (OK)", "os", "linux", None, "low", None, None, None),
    ("B64", "OS filesystem.used_mb 부동소수점 오차", "os", "linux", None, "med",
     "df -B1 / 1048576 변환 시 float 결과를 int 변환 안 함.",
     "df 출력 단위 + Jinja2 변환식",
     "os-gather/tasks/linux/normalize_storage.yml filesystems"),
    ("B65", "OS filesystem.free_mb=None 모든 fs", "os", "linux", None, "high",
     "df 결과에서 used만 추출, free 누락.",
     "df 출력 컬럼 매핑",
     "os-gather/tasks/linux/normalize_storage.yml"),
    ("B66", "OS filesystem.read_only=None 모든 fs", "os", "linux", None, "low",
     "/proc/mounts 또는 findmnt -o OPTIONS에서 ro/rw 추출.",
     "/proc/mounts 또는 findmnt 출력",
     "os-gather/tasks/linux/normalize_storage.yml"),
    ("B67", "OS filesystem.fstype (B26 동일)", "os", "linux", "B26", "med", None, None, None),
    ("B68", "OS network IPv6 address 0개", "os", "linux", None, "med",
     "ip -6 addr 또는 ansible_facts의 ipv6 address.",
     "ip -6 addr 출력 + ansible_facts.ipv6",
     "os-gather/tasks/linux/normalize_network.yml addresses"),
    ("B69", "ESXi network IPv6 0개", "esxi", "vmware", None, "low",
     "vSphere VirtualNicSpec.ipv6Spec 추출. 환경 의존.",
     "vSphere vmkernel ipv6 응답",
     "esxi-gather/tasks/normalize_network.yml"),
    ("B70", "r760-6 Redfish adapter.name='Network Adapter View'", "redfish", "dell", None, "low",
     "NetworkAdapter[].Name이 'Network Adapter View'(의미 없음). Description 또는 Model 사용.",
     "Dell /NetworkAdapters/{id} 의 Name/Description/Model",
     "redfish-gather/library normalize_adapter"),
    ("B71", "r760-6 memory.mfg drift (B23 동일)", "cross", "dell", "B23", "med", None, None, None),
    ("B72", "r760-6 memory.speed drift (B24 동일)", "cross", "dell", "B24", "med", None, None, None),
    ("B73", "OS hostname/fqdn drift (B18 동일)", "os", "linux", "B18", "med", None, None, None),
    ("B74", "swap_used (OK 관찰)", "os", "linux", None, "low", None, None, None),
    ("B75", "OS memory.visible_mb 필드명 명확화", "os", "linux", None, "low",
     "visible_mb < total_mb (kernel reserved). 'available_to_os_mb'로 변경 또는 문서.",
     "정책",
     "schema/field_dictionary.yml"),
    ("B76", "OS network.adapters=[] hardware NIC 미수집", "os", "linux", None, "med",
     "lspci -k -d ::0200 또는 dmidecode로 PCI NIC 수집.",
     "lspci -k -d ::0200 출력",
     "os-gather/tasks/linux/gather_hardware.yml + normalize_network.yml"),
    ("B77", "correlation 필드 일관성 (B81 동일)", "global", "all", "B81", "low", None, None, None),
    ("B78", "OS VM serial_number raw VMware 형식", "os", "linux VM", None, "med",
     "dmidecode raw 'VMware-42 04 c1 6d 6a...' 16-byte hex. 정규화.",
     "VM dmidecode -s system-serial-number 출력",
     "os-gather/tasks/linux/normalize_hardware.yml"),
    ("B79", "OS correlation.bmc_ip=None (정책)", "os", "linux", None, "low", None, None, None),
    ("B80", "OS envelope.vendor=None (베어메탈도)", "os", "linux", None, "med",
     "베어메탈은 dmidecode로 vendor 추출 가능. envelope.vendor 채우기.",
     "베어메탈 r760-6 dmidecode -s system-manufacturer",
     "os-gather/tasks/linux/normalize_hardware.yml + build_output.yml"),
    ("B81", "target_type별 envelope.vendor 정책 다름", "global", "all", None, "med",
     "OS=None, ESXi=cisco, Redfish=dell. 통일 정책.",
     "정책 결정",
     "common/tasks/normalize/build_output.yml + 각 채널 site.yml"),
    ("B82", "RHEL VM hostname=localhost (관찰)", "os", "linux", None, "low", None, None, None),
    ("B83", "ESXi hostname=esxi01 short name", "esxi", "vmware", None, "low", None, None, None),
    ("B84", "ESXi datastore precision (OK 검증)", "esxi", "vmware", None, "low", None, None, None),
    ("B85", "RHEL tz (B27 동일)", "os", "linux", "B27", "low", None, None, None),
    ("B86", "RHEL hostname (B82 동일)", "os", "linux", "B82", "low", None, None, None),
    ("B87", "OS sys.hostname (B18 동일)", "os", "linux", "B18", "med", None, None, None),
    ("B88", "ESXi correlation.bmc_ip=None (정책)", "esxi", "vmware", None, "low", None, None, None),
    ("B89", "r760-1 memory Samsung+Hynix 혼합 (관찰)", "redfish", "dell", None, "low", None, None, None),
    ("B90", "Cisco memory.mfg=0xCE00 raw JEDEC", "redfish", "cisco", None, "med",
     "CIMC가 Manufacturer를 raw 0xCExx로 반환. JEDEC ID -> name 매핑.",
     "Cisco /Systems/.../Memory/{id}.Manufacturer 응답",
     "redfish-gather/library normalize_memory + JEDEC map"),
    ("B91", "RHEL 8.10 raw_fallback memory.mfg=None", "os", "linux", None, "med",
     "raw fallback build_memory가 manufacturer 추출 누락.",
     "raw 모드 dmidecode -t memory 출력",
     "os-gather/tasks/linux/normalize_memory.yml raw 분기"),
    ("B92", "HPE iface.name 숫자만", "redfish", "hpe", None, "med",
     "HPE EthernetInterface.Id가 숫자(9,10,...). Name/Description 사용 + slot/port mapping.",
     "HPE EthernetInterface 전체 응답",
     "redfish-gather/library normalize_iface HPE 분기"),
    ("B93", "HPE adapter.mac/link 모두 None", "redfish", "hpe", None, "med",
     "HPE NetworkAdapter는 mac/link 없음 - ports[*]에 있음. 빌더가 ports를 fold-in 안 함.",
     "HPE /NetworkAdapters/{id}/Ports/{id} 응답",
     "redfish-gather/library normalize_adapter HPE 분기"),
    ("B94", "HPE iface.addresses 0개 (관찰)", "redfish", "hpe", None, "low", None, None, None),
    ("B95", "Lenovo PSU Critical 알람 (B58 동일)", "redfish", "lenovo", "B58", "high", None, None, None),
    ("B96", "ESXi collection_method=vsphere_api (OK)", "esxi", "vmware", None, "low", None, None, None),
    ("B97", "OS collection_method='agent' 모호", "os", "linux", None, "low",
     "ssh/winrm/raw 분기 명시. 'ansible_ssh', 'ansible_winrm', 'ansible_ssh_raw' 등.",
     "_l_python_mode + 채널 정보",
     "common/tasks/normalize/build_output.yml"),
    ("B98", "bios_date 형식 (B16 동일)", "global", "all", "B16", "med", None, None, None),
    ("B99", "listening_ports = list of int 구조화", "os", "linux", None, "low",
     "[22,53,...] -> [{port,proto,family,bind_address}].",
     "ss -tnlp 출력",
     "os-gather/tasks/linux/normalize_runtime.yml"),
]


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for tid, title, channel, vendor, dup_of, severity, hypothesis, evidence, fix_target in TICKETS:
        state = "dup" if dup_of else "proposed"
        body = (
            f"# {tid}: {title}\n\n"
            f"Status: {state}\n"
            f"Severity: {severity}\n"
            f"Channel: {channel}\n"
            f"Vendor: {vendor}\n"
        )
        if dup_of:
            body += f"Dup-of: {dup_of}\n"
        body += "\n## 증상\n\n(INDEX.md 참조)\n\n"
        body += f"## 가설\n\n{hypothesis or '(N/A)'}\n\n"
        body += f"## 검증할 raw 데이터\n\n{evidence or '(N/A)'}\n\n"
        body += f"## fix 위치 (가설)\n\n{fix_target or '(N/A)'}\n\n"
        body += (
            "## 검증 절차 (rule 28 + rule 95)\n\n"
            "- [ ] Jenkins agent (10.100.64.154)에서 raw 외부 API 응답 capture\n"
            "- [ ] 증상 재현\n"
            "- [ ] fix 위치 코드 검토\n"
            "- [ ] pytest fixture 추가 (raw 응답 기반)\n"
            "- [ ] 회귀 테스트 (RED)\n"
            "- [ ] 코드 fix (GREEN)\n"
            "- [ ] verify_harness_consistency / verify_vendor_boundary 통과\n"
            "- [ ] lab re-run 3회 - 누락/중복/drift 0건\n"
            "- [ ] evidence 첨부 + closed\n\n"
            "## evidence\n\n(채워질 자리)\n"
        )
        fpath = OUT_DIR / f"{tid}.md"
        fpath.write_text(body, encoding="utf-8")
        written += 1
    print(f"wrote {written} tickets to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
