#!/usr/bin/env bash
# install-git-hooks.sh — server-exporter git hooks 설치
#
# 설치 항목:
# - pre-commit: pre_commit_policy + pre_commit_harness_drift + pre_commit_skill_guard
#               + pre_commit_jenkinsfile_guard
# - commit-msg: commit_msg_check (rule 90)
# - post-commit: post_commit_measurement_trigger (rule 28)
# - post-merge: post_merge_gap_check + post_merge_incoming_review (rule 97)
#
# Usage:
#   bash scripts/ai/hooks/install-git-hooks.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOKS_DIR="${REPO_ROOT}/.git/hooks"
SCRIPTS_DIR="${REPO_ROOT}/scripts/ai/hooks"

if [[ ! -d "$HOOKS_DIR" ]]; then
    echo "ERROR: .git/hooks/ 디렉터리 없음: $HOOKS_DIR" >&2
    exit 1
fi

if [[ ! -d "$SCRIPTS_DIR" ]]; then
    echo "ERROR: scripts/ai/hooks/ 디렉터리 없음: $SCRIPTS_DIR" >&2
    exit 1
fi

PYTHON="${PYTHON:-python}"

write_hook() {
    local name="$1"
    shift
    local hook_path="${HOOKS_DIR}/${name}"

    cat > "$hook_path" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/ai/hooks/install-git-hooks.sh
# 다중 hook을 순차 실행. 하나라도 exit 2면 commit/merge 차단.

set -e

REPO_ROOT="\$(git rev-parse --show-toplevel)"
cd "\$REPO_ROOT"

EOF

    for script in "$@"; do
        cat >> "$hook_path" <<EOF
"\${PYTHON:-${PYTHON}}" scripts/ai/hooks/${script} "\$@" || exit \$?

EOF
    done

    chmod +x "$hook_path"
    echo "  installed: ${name}"
}

echo "Installing git hooks..."
write_hook "pre-commit" \
    "pre_commit_policy.py" \
    "pre_commit_harness_drift.py" \
    "pre_commit_skill_guard.py" \
    "pre_commit_jenkinsfile_guard.py"

write_hook "commit-msg" \
    "commit_msg_check.py"

write_hook "post-commit" \
    "post_commit_measurement_trigger.py"

write_hook "post-merge" \
    "post_merge_gap_check.py" \
    "post_merge_incoming_review.py"

echo "Done. PYTHON=${PYTHON} (override with: PYTHON=python3 bash $0)"
echo ""
echo "비활성화 환경변수:"
echo "  HARNESS_DRIFT_SKIP=1     — pre_commit_harness_drift skip"
echo "  PRE_COMMIT_POLICY_SKIP=1 — pre_commit_policy skip"
echo "  SKILL_GUARD_SKIP=1       — pre_commit_skill_guard skip"
echo "  JENKINSFILE_GUARD_SKIP=1 — pre_commit_jenkinsfile_guard skip"
echo "  POST_MERGE_GAP_SKIP=1    — post_merge_gap_check skip"
echo "  INCOMING_REVIEW_SKIP=1   — post_merge_incoming_review skip"
