#!/usr/bin/env bash
# install-git-hooks.sh — server-exporter git hooks 설치
#
# 설치 항목:
# - pre-commit: pre_commit_harness_drift + pre_commit_skill_guard
#               + pre_commit_jenkinsfile_guard
#               + pre_commit_docs20_sync_check (rule 13 R7 — cycle 2026-05-07 advisory / cycle 2026-05-11 BLOCKING 격상)
#               + pre_commit_status_logic_check (rule 13 R8 — cycle 2026-05-06-post advisory / cycle 2026-05-11 BLOCKING 격상)
#               + pre_commit_ticket_consistency (cold-start 6 절)
#               + pre_commit_additive_only_check (rule 92 R2 / 96 R1-B)
#               + pre_commit_jinja_namespace_check (rule 22 R7 — cycle 2026-05-07 advisory / cycle 2026-05-11 BLOCKING 격상)
#               + pre_commit_fragment_skeleton_sync (rule 22 R7 — cycle 2026-05-07)
# - commit-msg: commit_msg_check (rule 90)
# - post-commit: post_commit_measurement_trigger (rule 28)
#                + post_commit_compatibility_matrix_check (rule 28 #12)
# - post-merge: post_merge_gap_check + post_merge_incoming_review (rule 97)
#
# Usage:
#   bash scripts/ai/hooks/install-git-hooks.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOKS_DIR="${REPO_ROOT}/.git/hooks"
SCRIPTS_DIR="${REPO_ROOT}/scripts/ai/hooks"

if [[ ! -d "$HOOKS_DIR" ]]; then
    echo "ERROR: .git/hooks/ 디렉터리 없음: $HOOKS_DIR" >&2
    exit 1
fi

if [[ ! -d "$SCRIPTS_DIR" ]]; then
    echo "ERROR: scripts/ai/hooks/ 디렉터리 없음: $SCRIPTS_DIR" >&2
    exit 1
fi

PYTHON="${PYTHON:-python}"

write_hook() {
    local name="$1"
    shift
    local hook_path="${HOOKS_DIR}/${name}"

    cat > "$hook_path" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/ai/hooks/install-git-hooks.sh
# 다중 hook을 순차 실행. 하나라도 exit 2면 commit/merge 차단.

set -e

REPO_ROOT="\$(git rev-parse --show-toplevel)"
cd "\$REPO_ROOT"

EOF

    for script in "$@"; do
        cat >> "$hook_path" <<EOF
"\${PYTHON:-${PYTHON}}" scripts/ai/hooks/${script} "\$@" || exit \$?

EOF
    done

    chmod +x "$hook_path"
    echo "  installed: ${name}"
}

echo "Installing git hooks..."
write_hook "pre-commit" \
    "pre_commit_harness_drift.py" \
    "pre_commit_skill_guard.py" \
    "pre_commit_jenkinsfile_guard.py" \
    "pre_commit_docs20_sync_check.py" \
    "pre_commit_status_logic_check.py" \
    "pre_commit_ticket_consistency.py" \
    "pre_commit_additive_only_check.py" \
    "pre_commit_jinja_namespace_check.py" \
    "pre_commit_fragment_skeleton_sync.py"

write_hook "commit-msg" \
    "commit_msg_check.py"

write_hook "post-commit" \
    "post_commit_measurement_trigger.py" \
    "post_commit_compatibility_matrix_check.py"

write_hook "post-merge" \
    "post_merge_gap_check.py" \
    "post_merge_incoming_review.py"

echo "Done. PYTHON=${PYTHON} (override with: PYTHON=python3 bash $0)"
echo ""
echo "비활성화 환경변수:"
echo "  HARNESS_DRIFT_SKIP=1          — pre_commit_harness_drift skip"
echo "  SKILL_GUARD_SKIP=1            — pre_commit_skill_guard skip"
echo "  JENKINSFILE_GUARD_SKIP=1      — pre_commit_jenkinsfile_guard skip"
echo "  DOCS20_SYNC_SKIP=1            — pre_commit_docs20_sync_check skip (rule 13 R7, BLOCKING cycle 2026-05-11)"
echo "  DOCS20_SYNC_SKIP_COSMETIC=1   — cosmetic only commit (rule 13 R7 Allowed)"
echo "  STATUS_LOGIC_SKIP=1           — pre_commit_status_logic_check skip (rule 13 R8, BLOCKING cycle 2026-05-11)"
echo "  STATUS_LOGIC_SKIP_COSMETIC=1  — cosmetic only commit (rule 13 R8 Allowed)"
echo "  TICKET_CONSISTENCY_SKIP=1     — pre_commit_ticket_consistency skip (cold-start 6 절)"
echo "  ADDITIVE_SKIP=1               — pre_commit_additive_only_check skip (rule 92 R2 / 96 R1-B)"
echo "  ADDITIVE_SKIP_NEW_CYCLE=1     — 새 cycle (호환성 외) 명시 skip"
echo "  COMPAT_MATRIX_CHECK_SKIP=1    — post_commit_compatibility_matrix_check skip (rule 28 #12)"
echo "  POST_MERGE_GAP_SKIP=1         — post_merge_gap_check skip"
echo "  INCOMING_REVIEW_SKIP=1        — post_merge_incoming_review skip"
echo "  JINJA_NAMESPACE_SKIP=1        — pre_commit_jinja_namespace_check skip (rule 22 R7, BLOCKING cycle 2026-05-11)"
echo "  JINJA_NAMESPACE_SKIP_FILE=... — 특정 파일만 skip (':' 구분)"
echo "  SKELETON_SYNC_SKIP=1          — pre_commit_fragment_skeleton_sync skip (rule 22 R7, blocking)"
